// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: balance/v1/ocp_balance_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ocp.balance.v1.Balance

/// Namespace containing generated types for the "ocp.balance.v1.Balance" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Ocp_Balance_V1_Balance {
    /// Service descriptor for the "ocp.balance.v1.Balance" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ocp.balance.v1.Balance")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "GetBalance" metadata.
        public enum GetBalance {
            /// Request type for "GetBalance".
            public typealias Input = Ocp_Balance_V1_GetBalanceRequest
            /// Response type for "GetBalance".
            public typealias Output = Ocp_Balance_V1_GetBalanceResponse
            /// Descriptor for "GetBalance".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ocp.balance.v1.Balance"),
                method: "GetBalance"
            )
        }
        /// Descriptors for all methods in the "ocp.balance.v1.Balance" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetBalance.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ocp.balance.v1.Balance" service.
    public static let ocp_balance_v1_Balance = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ocp.balance.v1.Balance")
}

// MARK: ocp.balance.v1.Balance (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Ocp_Balance_V1_Balance {
    /// Generated client protocol for the "ocp.balance.v1.Balance" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetBalance" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetBalance returns balance data for any owner account
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ocp_Balance_V1_GetBalanceRequest` message.
        ///   - serializer: A serializer for `Ocp_Balance_V1_GetBalanceRequest` messages.
        ///   - deserializer: A deserializer for `Ocp_Balance_V1_GetBalanceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getBalance<Result>(
            request: GRPCCore.ClientRequest<Ocp_Balance_V1_GetBalanceRequest>,
            serializer: some GRPCCore.MessageSerializer<Ocp_Balance_V1_GetBalanceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ocp_Balance_V1_GetBalanceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ocp_Balance_V1_GetBalanceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ocp.balance.v1.Balance" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetBalance" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetBalance returns balance data for any owner account
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ocp_Balance_V1_GetBalanceRequest` message.
        ///   - serializer: A serializer for `Ocp_Balance_V1_GetBalanceRequest` messages.
        ///   - deserializer: A deserializer for `Ocp_Balance_V1_GetBalanceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getBalance<Result>(
            request: GRPCCore.ClientRequest<Ocp_Balance_V1_GetBalanceRequest>,
            serializer: some GRPCCore.MessageSerializer<Ocp_Balance_V1_GetBalanceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ocp_Balance_V1_GetBalanceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ocp_Balance_V1_GetBalanceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ocp_Balance_V1_Balance.Method.GetBalance.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Ocp_Balance_V1_Balance.ClientProtocol {
    /// Call the "GetBalance" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetBalance returns balance data for any owner account
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ocp_Balance_V1_GetBalanceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBalance<Result>(
        request: GRPCCore.ClientRequest<Ocp_Balance_V1_GetBalanceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ocp_Balance_V1_GetBalanceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getBalance(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ocp_Balance_V1_GetBalanceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ocp_Balance_V1_GetBalanceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Ocp_Balance_V1_Balance.ClientProtocol {
    /// Call the "GetBalance" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetBalance returns balance data for any owner account
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBalance<Result>(
        _ message: Ocp_Balance_V1_GetBalanceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ocp_Balance_V1_GetBalanceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ocp_Balance_V1_GetBalanceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getBalance(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}