// Generated by scripts/generate-swift.sh. Do not edit.

public enum OCPContractInfo {
    public static let version = "0.5.0-dev"
    public static let protoCommit = "e3d25a85b1e1ce088e956714e1a71248322e215f"

    public static var isLocal: Bool { protoCommit == localSentinel }

    public static var shortProtoCommit: String {
        isLocal ? protoCommit : String(protoCommit.prefix(shortLength))
    }

    private static let localSentinel = "LOCAL"
    private static let shortLength = 8
}
