// Generated by scripts/generate-swift.sh. Do not edit.

public enum OCPContractInfo {
    public static let version = "0.5.0-dev"
    public static let protoCommit = "82202912574e122bba90025fe8b292d5a3f04c05"

    public static var isLocal: Bool { protoCommit == localSentinel }

    public static var shortProtoCommit: String {
        isLocal ? protoCommit : String(protoCommit.prefix(shortLength))
    }

    private static let localSentinel = "LOCAL"
    private static let shortLength = 8
}
