#!/usr/bin/env bash
#
# Generate the Swift client from proto/ into Sources/OCPClientProtocol/.
# Output is committed: SPM ships plain source, so the generated code is the artifact.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_DIR="$ROOT/proto"
DEPS_DIR="$ROOT/proto_deps"
WKT_DIR="$ROOT/.tools/include"
OUT="$ROOT/Sources/OCPClientProtocol"

# Prefer the pinned toolchain. Generated Swift is version-sensitive -- a newer
# protoc-gen-swift rewrites hundreds of lines with no contract change -- so an ambient
# brew install is not a substitute. See scripts/toolchain.env.
export PATH="$ROOT/.tools/bin:$PATH"

for tool in protoc protoc-gen-swift protoc-gen-grpc-swift-2; do
  command -v "$tool" >/dev/null || {
    echo "missing $tool -- run scripts/install-swift-toolchain.sh" >&2; exit 1; }
done

rm -rf "$OUT"
mkdir -p "$OUT"

# validate/validate.proto is an include-path dependency only. It is never generated --
# swift-protobuf would emit a validate_validate.pb.swift that the app then has to delete,
# which is what the iOS Scripts/run hack was working around.
while IFS= read -r f; do
  rel="${f#"$PROTO_DIR"/}"

  protoc -I"$PROTO_DIR" -I"$DEPS_DIR" -I"$WKT_DIR" "$rel" \
    --swift_opt=Visibility=Public \
    --swift_opt=FileNaming=PathToUnderscores \
    --swift_out="$OUT"

  # gRPC stubs only for files that declare a service.
  if grep -q '^service ' "$f"; then
    protoc -I"$PROTO_DIR" -I"$DEPS_DIR" -I"$WKT_DIR" "$rel" \
      --grpc-swift-2_opt=Visibility=Public \
      --grpc-swift-2_opt=Server=false \
      --grpc-swift-2_opt=Client=true \
      --grpc-swift-2_opt=FileNaming=PathToUnderscores \
      --grpc-swift-2_out="$OUT"
  fi
done < <(cd "$PROTO_DIR" && find . -name '*.proto' -type f | sed "s#^\./#$PROTO_DIR/#" | sort)

# ContractInfo is the one hand-written file in this directory, and it has to be written
# here rather than by sync-protos.sh: OUT is wiped above, so anything sync writes would
# not survive a regenerate. On main the version is the next CHANGELOG entry plus -dev;
# publish.yml re-runs this with RELEASE_VERSION set and commits the result onto the tag.
commit="$(awk '/^commit:/ {print $2}' "$ROOT/ocp.lock")"
[ -n "$commit" ] || { echo "ocp.lock: no commit: line" >&2; exit 1; }

version="${RELEASE_VERSION:-}"
if [ -z "$version" ]; then
  changelog_version="$(awk '/^## / {print $2; exit}' "$ROOT/CHANGELOG.md")"
  [ -n "$changelog_version" ] || { echo "CHANGELOG.md: no '## <version>' heading" >&2; exit 1; }
  version="${changelog_version}-dev"
fi

cat > "$OUT/ContractInfo.swift" <<SWIFT_EOF
// Generated by scripts/generate-swift.sh. Do not edit.

public enum OCPContractInfo {
    public static let version = "$version"
    public static let protoCommit = "$commit"

    public static var isLocal: Bool { protoCommit == localSentinel }

    public static var shortProtoCommit: String {
        isLocal ? protoCommit : String(protoCommit.prefix(shortLength))
    }

    private static let localSentinel = "LOCAL"
    private static let shortLength = 8
}
SWIFT_EOF

echo "==> generated $(find "$OUT" -name '*.swift' | wc -l | tr -d ' ') Swift file(s) into Sources/OCPClientProtocol/"
echo "==> ContractInfo.swift: $version / $commit"
